# Generated by Django 2.2.4 on 2020-02-07 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_profile',
            fields=[
                ('company_useremail', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('company_userpassword', models.CharField(max_length=1000)),
                ('company_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(default='', max_length=15)),
                ('website_url', models.CharField(max_length=255)),
                ('password_updated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.userrole')),
            ],
        ),
    ]
