# Generated by Django 2.2.4 on 2020-02-07 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_company_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='hr_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_firstname', models.CharField(max_length=255)),
                ('hr_lastname', models.CharField(max_length=255)),
                ('hr_fullname', models.CharField(default='', max_length=255)),
                ('hr_email', models.EmailField(max_length=255)),
                ('hr_password', models.CharField(max_length=1000)),
                ('hr_mobile', models.CharField(default='', max_length=15)),
                ('is_active', models.BooleanField(default=False)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.userrole')),
            ],
        ),
    ]
