# Generated by Django 2.2.4 on 2020-02-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_hr_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_firstname', models.CharField(max_length=255)),
                ('emp_lastname', models.CharField(max_length=255)),
                ('emp_fullname', models.CharField(default='', max_length=255)),
                ('emp_email', models.EmailField(default='', max_length=255)),
                ('emp_password', models.CharField(max_length=1000)),
                ('emp_mobile', models.CharField(default='', max_length=10)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.userrole')),
            ],
        ),
    ]
