# Generated by Django 2.2.4 on 2020-02-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_emp_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_profile',
            old_name='company_useremail',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='company_profile',
            old_name='company_userpassword',
            new_name='company_password',
        ),
    ]
